In [2]:
import json
import pandas as pd
from harmonizer.harmonizer import FashionHarmonizer
from ast import literal_eval

In [3]:
with open('data/male/male-types-with-parameters.json') as f:
    female_types_with_parameters = json.load(f)
with open('data/male/male-types.json') as f:
    female_types = json.load(f)
with open('data/type-parameters.json') as f:
    type_parameters = json.load(f)
with open('data/male/male-style-type.json') as f:
    gender_style_type = json.load(f)

In [4]:
def get_value(list_values,column):
    if type(list_values)!=list:
        return list_values
    interim=[]
    for i in range(len(list_values)):
        interim.append(list_values[i][column])
    return interim

In [5]:
gender_types_df=pd.DataFrame(female_types)
gender_types_with_parameters_df=pd.DataFrame(female_types_with_parameters)
type_parameters_df=pd.DataFrame(type_parameters)
        # merge to get parameter for each type
df=gender_types_df.merge(gender_types_with_parameters_df, left_on='type', right_on='clothes_type',how='left')
        #flatten df to get more explicit view
df['clothesParameters']=df.parameters.apply(lambda x: get_value(x,'name'))
# df=df[['category','subcategory','type','clothesParameters']].explode('clothesParameters')

In [6]:
df.parameters[0]

[{'name': 'fit', 'values': ['regular', 'oversize']}]

In [8]:
with open('data/female/female-types-with-parameters.json') as f:
    female_types_with_parameters = json.load(f)
with open('data/female/female-types.json') as f:
    female_types = json.load(f)
with open('data/type-parameters.json') as f:
    type_parameters = json.load(f)
with open('data/female/female-style-type.json') as f:
    gender_style_type = json.load(f)

In [7]:
ex = FashionHarmonizer(gender_types_with_parameters=female_types_with_parameters, 
                       gender_types=female_types, 
                       type_parameters=type_parameters,
                       gender_style_type=gender_style_type)

In [8]:
ex.transform_jsons_flatten_df()

In [9]:
ex.main_df

,category,subcategory,type,clothesParameters,values,priorityProb
0,top,hoodies&sweatshirts,sweatshirt,length,cropped,1.0
0,top,hoodies&sweatshirts,sweatshirt,length,regular,1.0
0,top,hoodies&sweatshirts,sweatshirt,length,extended,1.0
1,top,hoodies&sweatshirts,sweatshirt,fit,slim,1.0
1,top,hoodies&sweatshirts,sweatshirt,fit,regular,1.0
...,...,...,...,...,...,...
85,footwear,pumps,dress_sandals,heel_type,platform,1.0
85,footwear,pumps,dress_sandals,heel_type,heel,1.0
85,footwear,pumps,dress_sandals,heel_type,flat,1.0
86,footwear,flats&loafers,flats,NaN,NaN,1.0
87,footwear,flats&loafers,loafers,NaN,NaN,1.0

In [10]:
ex.filter_type_by_style(style_type='casual')

In [11]:
ex.main_df

,category,subcategory,type,clothesParameters,values,priorityProb,styleType
0,top,hoodies&sweatshirts,sweatshirt,length,cropped,1.0,casual
1,top,hoodies&sweatshirts,sweatshirt,length,regular,1.0,casual
2,top,hoodies&sweatshirts,sweatshirt,length,extended,1.0,casual
3,top,hoodies&sweatshirts,sweatshirt,fit,slim,1.0,casual
4,top,hoodies&sweatshirts,sweatshirt,fit,regular,1.0,casual
...,...,...,...,...,...,...,...
215,footwear,boots,ankle_boots,heel_type,platform,1.0,casual
216,footwear,boots,ankle_boots,heel_type,heel,1.0,casual
217,footwear,boots,ankle_boots,heel_type,flat,1.0,casual
218,footwear,flats&loafers,flats,NaN,NaN,1.0,casual
219,footwear,flats&loafers,loafers,NaN,NaN,1.0,casual

In [12]:
ex.main_df.to_csv('female_clothes.csv')

In [13]:
with open('data/male/male-body-type-rules.json') as f:
    male_body_rules = json.load(f)

In [14]:
ex.assign_priority_clothingtype_rule(value='rectangle',rule_path='data/male-body-type-rules.json')

In [15]:
ex.main_df

,category,subcategory,type,clothesParameters,values,styleType,priorityProb
0,top,hoodies&sweatshirts,sweatshirt,length,cropped,casual,1.0
1,top,hoodies&sweatshirts,sweatshirt,length,regular,casual,1.0
2,top,hoodies&sweatshirts,sweatshirt,length,extended,casual,1.0
3,top,hoodies&sweatshirts,sweatshirt,fit,slim,casual,1.0
4,top,hoodies&sweatshirts,sweatshirt,fit,regular,casual,1.0
...,...,...,...,...,...,...,...
215,footwear,boots,ankle_boots,heel_type,platform,casual,1.0
216,footwear,boots,ankle_boots,heel_type,heel,casual,1.0
217,footwear,boots,ankle_boots,heel_type,flat,casual,1.0
218,footwear,flats&loafers,flats,NaN,NaN,casual,1.0
219,footwear,flats&loafers,loafers,NaN,NaN,casual,1.0

In [16]:
ex.assign_priority_outfit_by_rules(gender='male', style='casual', season='')

,category,transcriptTypeParams,subcategory,type,paramCombinations,clothesParameters,values
0,outerwear,denim_jacket,jackets,denim_jacket,empty,empty,empty
1,top,fit-oversize linen_shirt,shirts,linen_shirt,fit-oversize,fit,oversize
2,bottom,fit-wide waist-regular length-regular joggers,trousers,joggers,fit-wide,fit,wide
3,bottom,fit-wide waist-regular length-regular joggers,trousers,joggers,waist-regular,waist,regular
4,bottom,fit-wide waist-regular length-regular joggers,trousers,joggers,length-regular,length,regular
...,...,...,...,...,...,...,...
3,top,length-regular fit-oversize neckline-round_nec...,t-shirts,t-shirt,neckline-round_neck,neckline,round_neck
4,bottom,waist-regular fit-wide length-regular jeans,jeans,jeans,waist-regular,waist,regular
5,bottom,waist-regular fit-wide length-regular jeans,jeans,jeans,fit-wide,fit,wide
6,bottom,waist-regular fit-wide length-regular jeans,jeans,jeans,length-regular,length,regular
7,footwear,chelsea_boots,boots,chelsea_boots,empty,empty,empty

 # chernovik

# stage 2

In [45]:
import json
import pandas as pd
from ast import literal_eval
gender='female'
style='casual'

with open(f'data_combinations/cartesian_product/{gender}_{style}_outerwear.json') as f:
    d = json.load(f)

In [46]:
style_clothes_transcript=pd.read_csv('data_combinations/female_style_clothing_transcript.csv',index_col=0)[['category','subcategory','type','transcriptTypeParams','paramCombinations']]
style_clothes_transcript['paramCombinations']=style_clothes_transcript['paramCombinations'].apply(lambda x: literal_eval if type(x)==list else x)

In [47]:
def split_correct(text,numb):
    if text=='empty':
        return text
    return text.split('-',1)[numb]

def get_parsed_cartesian_outfit(outfit, upper_clothes_category,  style_clothes_transcript):
    interim=pd.DataFrame(outfit).T.set_axis([upper_clothes_category,'top','bottom','footwear'],axis=1).T.reset_index(drop=False).rename(columns={'index':'category',0:'transcriptTypeParams'})
    interim=interim.merge(style_clothes_transcript,on=['transcriptTypeParams','category'])
    interim['paramCombinations']=interim['paramCombinations'].apply(lambda x: literal_eval(x) if type(x)!=float else x)
    interim=interim.explode('paramCombinations').reset_index(drop=True).fillna('empty')
    interim['clothesParameters']=interim.paramCombinations.apply(lambda x: split_correct(x,0))
    interim['values']=interim.paramCombinations.apply(lambda x: split_correct(x,1))
    return interim

In [48]:
main_df

,category,subcategory,type,clothesParameters,values,styleType,priorityProb
0,top,hoodies&sweatshirts,sweatshirt,length,cropped,casual,1.0
1,top,hoodies&sweatshirts,sweatshirt,length,regular,casual,1.0
2,top,hoodies&sweatshirts,sweatshirt,length,extended,casual,1.0
3,top,hoodies&sweatshirts,sweatshirt,fit,slim,casual,1.0
4,top,hoodies&sweatshirts,sweatshirt,fit,regular,casual,1.0
...,...,...,...,...,...,...,...
215,footwear,boots,ankle_boots,heel_type,platform,casual,1.0
216,footwear,boots,ankle_boots,heel_type,heel,casual,1.0
217,footwear,boots,ankle_boots,heel_type,flat,casual,1.0
218,footwear,flats&loafers,flats,empty,empty,casual,1.0
219,footwear,flats&loafers,loafers,empty,empty,casual,1.0

In [26]:
main_df = ex.main_df
main_df=main_df.fillna('empty')

In [65]:
interim.merge(main_df[main_df['priorityProb']!=1.0],on=['type','clothesParameters','values'],how='left').fillna(1).groupby(['category_x'])['priorityProb'].prod()

category_x
bottom       1.0
footwear     1.0
outerwear    1.0
top          1.0
Name: priorityProb, dtype: float64

In [60]:
interim

,category,transcriptTypeParams,subcategory,type,paramCombinations,clothesParameters,values
0,outerwear,parka,jackets,parka,empty,empty,empty
1,top,neckline-V-neck crop_top,tops,crop_top,neckline-V-neck,neckline,V-neck
2,bottom,waist-high fit-tapered length-midi denim_skirt,skirts,denim_skirt,waist-high,waist,high
3,bottom,waist-high fit-tapered length-midi denim_skirt,skirts,denim_skirt,fit-tapered,fit,tapered
4,bottom,waist-high fit-tapered length-midi denim_skirt,skirts,denim_skirt,length-midi,length,midi
5,footwear,high-top_sneakers,sneakers,high-top_sneakers,empty,empty,empty

In [60]:
def assign_priority_outfit_by_rules(gender, style, season):

,category,subcategory,type,clothesParameters,values,styleType,priorityProb
0,top,hoodies&sweatshirts,sweatshirt,length,cropped,casual,1.0
1,top,hoodies&sweatshirts,sweatshirt,length,regular,casual,1.0
2,top,hoodies&sweatshirts,sweatshirt,length,extended,casual,1.0
3,top,hoodies&sweatshirts,sweatshirt,fit,slim,casual,1.0
4,top,hoodies&sweatshirts,sweatshirt,fit,regular,casual,1.0
...,...,...,...,...,...,...,...
215,footwear,boots,ankle_boots,heel_type,platform,casual,1.0
216,footwear,boots,ankle_boots,heel_type,heel,casual,1.0
217,footwear,boots,ankle_boots,heel_type,flat,casual,1.0
218,footwear,flats&loafers,flats,NaN,NaN,casual,1.0
219,footwear,flats&loafers,loafers,NaN,NaN,casual,1.0